### ISSUE TITLE
"startDate": "Invalid date", when importing LinkedIn Basic_LinkedInDataExport zip

### ISSUE THREAD

**Issue by sgiebels** [JMPerez/linkedin-to-json-resume#20]
With the most recent version of your demo website(which I used around 2018-01-28_15h50)

In the section "work", the dates are not parsed:
      "startDate": "Invalid date",
and
      "endDate": "Invalid date"

However, in my case, from the eduction section all start and end dates work ok (Perhaps because I entered only years in my education profile, without months)

additionally, the "summary" from the section "projects" is missing, as well as publications, and courses.

ps: on the demo website, instead of `Initial_LinkedInDataExport_XX-XX-XXXX.zip`, the filename format nowadays is `Basic_LinkedInDataExport_XX-XX-XXXX`, which is often ready within minutes. You might want to tell your demo website users that they do not have to wait for the `Complete_LinkedInDataExport_XX-XX-XXXX.zip` file.

Kind regards, and thanks again for this great tool!

**Comment by JMPerez** [comment]
Your issue referred to several issues.
- Invalid date should be fixed with https://github.com/JMPerez/linkedin-to-json-resume/pull/26
- Wrong file name should be fiexed with https://github.com/JMPerez/linkedin-to-json-resume/pull/27
- Publications were missing. Should be fixed on https://github.com/JMPerez/linkedin-to-json-resume/pull/28
- Courses can't be included since in JSON Resume they are bound to an education item and in the exported data from LinkedIn this relatioin doesn't exist.
- Projects don't exist in JSON Resume, afaik.
